name: Compare to meta-repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compare:
    uses: Nexus-Mods/NexusMods.App.Meta/.github/workflows/compare-to-meta.yaml@main
